import { ethers, artifacts, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * Deploys CredentialRegistry and exports its ABI + address into the web app
 * (web/src/lib/chain/generated.ts) so the frontend always talks to the exact
 * contract that was just deployed.
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`Deploying CredentialRegistry as ${deployer.address} on "${network.name}"...`);

  const Factory = await ethers.getContractFactory("CredentialRegistry");
  const registry = await Factory.deploy();
  await registry.waitForDeployment();

  const address = await registry.getAddress();
  console.log(`✓ CredentialRegistry deployed at: ${address}`);

  const artifact = await artifacts.readArtifact("CredentialRegistry");
  const out = `// AUTO-GENERATED by contracts/scripts/deploy.ts — do not edit by hand.
// Regenerated on every deploy so the ABI + address stay in sync with the contract.
export const CREDENTIAL_REGISTRY_ADDRESS = "${address}" as const;
export const CREDENTIAL_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  const target = path.resolve(__dirname, "../../web/src/lib/chain/generated.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, out);
  console.log(`✓ Wrote ABI + address to ${path.relative(process.cwd(), target)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
